### ISSUE TITLE
Sort gameslist with common games first

### ISSUE THREAD

**Issue by HansMerken** [dunguyen/whatshouldweplay-discord#90]
The bot outputs a randomized list of games.
The expected behavior is that games with a count of 1 should not be displayed.

![image](https://user-images.githubusercontent.com/1295074/103354909-1bbb7600-4aad-11eb-95a1-85366b02d21d.png)

![image](https://user-images.githubusercontent.com/1295074/103354945-35f55400-4aad-11eb-8a34-379853cc62f2.png)

In play.ts (33) you specify the default sort = SortOptions.Random
so it's always Random if you do not say anything else.

In userlibrary.ts (198) you have a switchcase with the default option which it will never hit due to the above.

you could set a condition for line 217 to be numberOwned > 1 or something similar.

**Comment by dunguyen** [comment]
The default should definitely be sorted after number of games owned. For random I see the value of ensuring more than one person owning the game, the other sorts I'll leave the option to have games owned by only one person shown to populate up to the limit of games shown
